### ISSUE TITLE
PyPi information missing source link

### ISSUE THREAD

**Issue by dsblank** [gkvoelkl/ipython-turtle-widget#1]
Thanks for sharing!

The setup.py info is missing a link to this repo:

https://github.com/gkvoelkl/ipython-turtle-widget

on this page:

https://pypi.python.org/pypi/ipyturtle/0.2.0

**Comment by dsblank** [comment]
Actually, it looks like the source isn't here yet.

**Comment by gkvoelkl** [comment]
Hi,

at the moment this project is under construction.

I have to do some tests. The first test was how to publish a well formatted README file. I hope until next week the project will be completed.

Best regards

Gerhard
