### ISSUE TITLE
Turtle not drawing a line

### ISSUE THREAD

**Issue by jamesf1234** [gkvoelkl/ipython-turtle-widget#21]
Tried a simple piece of code in Jupyter hub. The turtle moves but does not draw a line. Any ideas?

`from ipyturtle import Turtle

Bill = Turtle()
Bill.pencolor("Red")
Bill.pendown()
Bill.forward(100)
Bill.right(90)
Bill.forward(100)
Bill
#print (Bill.isdown())`

**Comment by gkvoelkl** [comment]
First this 2 lines in one cell

Bill = Turtle()
Bill

than all other commands 

After the first two lines the tutrtle exists and the communication between JavaScript and Python works
