### ISSUE TITLE
Wrong display of nested squares

### ISSUE THREAD

**Issue by ghost** [gkvoelkl/ipython-turtle-widget#6]
This is a minimal example of the wrong display

# Python 3.6.1, with IDLE on windows 10: it works

```python
import turtle as t

sideLength = 40
for square in range(5):
    for side in range(4):
        t.forward(sideLength)
        t.left(90)
    sideLength += 10
```
![image](https://user-images.githubusercontent.com/29369917/27024898-c8791748-4f58-11e7-9203-1ed5f0df2f77.png)

# With ``ipython-turtle-widget`` in Jupyter notebook() : wrong display

```python
from ipyturtle import Turtle
t = Turtle(fixed=False, width=200, height=200)
t
```
![image](https://user-images.githubusercontent.com/29369917/27025145-b14180aa-4f59-11e7-9c60-c5724c1520ac.png)

```python
sideLength = 40
for square in range(5):
    for side in range(4):
        t.forward(sideLength)
        t.left(90)
    sideLength += 10
```

# Why ?

Perhaps a rounding error in the angle of the turtle ? (floating value ?)
I can document this bug, but i can't fix it myself.

Thanks !

**Comment by gkvoelkl** [comment]
Thanks for documenting.

I will care.

Best regards Gerhard

**Comment by gkvoelkl** [comment]
fixed
