### ISSUE TITLE
Widget no longer renders in current notebook releases

### ISSUE THREAD

**Issue by psychemedia** [gkvoelkl/ipython-turtle-widget#7]
Installing `ipython-turtle-widget` into a current Jupyter notebook environment does not display the widget and fails with a `manager-base.js:273 Could not instantiate widget` error reported into the browser console. 

I suspect that the current widget definitions have moved on?

**Comment by gkvoelkl** [comment]
Which notebook environment do you use?

**Comment by psychemedia** [comment]
I'm trying it out on https://notebooks.azure.com :

````
!jupyter --version
4.4.0

!pip freeze | grep ipywidgets
ipywidgets==7.0.0b7
````

**Comment by gkvoelkl** [comment]
fixed
